### ISSUE TITLE
关于删除评论

### ISSUE THREAD

**Issue by isBoom** [sirodeneko/giligili-vue#2]
点击视频下方的删除本条评论时不论点击确定还是取消，弹出的框里的信息都是错的

**Comment by sirodeneko** [comment]
额，你可以登录进去吗，极验的验证码好像跪了，我回头看下

**Comment by isBoom** [comment]
很久之前登录的，最近没登陆，不过这个登录之后首页还有登录按钮，虽然有登陆的状态

**Comment by isBoom** [comment]
额，发现问题了 ，很久之前登陆的，今天上去，首页有登录按钮，但是有登录状态（大概），能评论，更改点击那个登录重新登录了，首页的登录变成个人中心了

**Comment by isBoom** [comment]
现在把点击删除评论，确定，之后的弹框由发布成功变成删除成功就行了

**Comment by sirodeneko** [comment]
接口莫名奇妙又好了，算了，以后有空再把聊天室写完更新下（咕咕咕）
